// GENERATED by tools/gen_jni_slots.py — do not edit.
// Source: ~/Library/Android/sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/jni.h
//
// Slot *order* is ABI. The guest indexes these tables directly; it never
// looks a name up. See runtime/kl_jni.c.
#ifndef KL_JNI_SLOTS_H
#define KL_JNI_SLOTS_H

// JNINativeInterface (JNIEnv) — 233 slots
#define KL_JNI_SLOTS_COUNT 233
#define KL_JNI_SLOTS(_) \
    _(  0, reserved0) \
    _(  1, reserved1) \
    _(  2, reserved2) \
    _(  3, reserved3) \
    _(  4, GetVersion) \
    _(  5, DefineClass) \
    _(  6, FindClass) \
    _(  7, FromReflectedMethod) \
    _(  8, FromReflectedField) \
    _(  9, ToReflectedMethod) \
    _( 10, GetSuperclass) \
    _( 11, IsAssignableFrom) \
    _( 12, ToReflectedField) \
    _( 13, Throw) \
    _( 14, ThrowNew) \
    _( 15, ExceptionOccurred) \
    _( 16, ExceptionDescribe) \
    _( 17, ExceptionClear) \
    _( 18, FatalError) \
    _( 19, PushLocalFrame) \
    _( 20, PopLocalFrame) \
    _( 21, NewGlobalRef) \
    _( 22, DeleteGlobalRef) \
    _( 23, DeleteLocalRef) \
    _( 24, IsSameObject) \
    _( 25, NewLocalRef) \
    _( 26, EnsureLocalCapacity) \
    _( 27, AllocObject) \
    _( 28, NewObject) \
    _( 29, NewObjectV) \
    _( 30, NewObjectA) \
    _( 31, GetObjectClass) \
    _( 32, IsInstanceOf) \
    _( 33, GetMethodID) \
    _( 34, CallObjectMethod) \
    _( 35, CallObjectMethodV) \
    _( 36, CallObjectMethodA) \
    _( 37, CallBooleanMethod) \
    _( 38, CallBooleanMethodV) \
    _( 39, CallBooleanMethodA) \
    _( 40, CallByteMethod) \
    _( 41, CallByteMethodV) \
    _( 42, CallByteMethodA) \
    _( 43, CallCharMethod) \
    _( 44, CallCharMethodV) \
    _( 45, CallCharMethodA) \
    _( 46, CallShortMethod) \
    _( 47, CallShortMethodV) \
    _( 48, CallShortMethodA) \
    _( 49, CallIntMethod) \
    _( 50, CallIntMethodV) \
    _( 51, CallIntMethodA) \
    _( 52, CallLongMethod) \
    _( 53, CallLongMethodV) \
    _( 54, CallLongMethodA) \
    _( 55, CallFloatMethod) \
    _( 56, CallFloatMethodV) \
    _( 57, CallFloatMethodA) \
    _( 58, CallDoubleMethod) \
    _( 59, CallDoubleMethodV) \
    _( 60, CallDoubleMethodA) \
    _( 61, CallVoidMethod) \
    _( 62, CallVoidMethodV) \
    _( 63, CallVoidMethodA) \
    _( 64, CallNonvirtualObjectMethod) \
    _( 65, CallNonvirtualObjectMethodV) \
    _( 66, CallNonvirtualObjectMethodA) \
    _( 67, CallNonvirtualBooleanMethod) \
    _( 68, CallNonvirtualBooleanMethodV) \
    _( 69, CallNonvirtualBooleanMethodA) \
    _( 70, CallNonvirtualByteMethod) \
    _( 71, CallNonvirtualByteMethodV) \
    _( 72, CallNonvirtualByteMethodA) \
    _( 73, CallNonvirtualCharMethod) \
    _( 74, CallNonvirtualCharMethodV) \
    _( 75, CallNonvirtualCharMethodA) \
    _( 76, CallNonvirtualShortMethod) \
    _( 77, CallNonvirtualShortMethodV) \
    _( 78, CallNonvirtualShortMethodA) \
    _( 79, CallNonvirtualIntMethod) \
    _( 80, CallNonvirtualIntMethodV) \
    _( 81, CallNonvirtualIntMethodA) \
    _( 82, CallNonvirtualLongMethod) \
    _( 83, CallNonvirtualLongMethodV) \
    _( 84, CallNonvirtualLongMethodA) \
    _( 85, CallNonvirtualFloatMethod) \
    _( 86, CallNonvirtualFloatMethodV) \
    _( 87, CallNonvirtualFloatMethodA) \
    _( 88, CallNonvirtualDoubleMethod) \
    _( 89, CallNonvirtualDoubleMethodV) \
    _( 90, CallNonvirtualDoubleMethodA) \
    _( 91, CallNonvirtualVoidMethod) \
    _( 92, CallNonvirtualVoidMethodV) \
    _( 93, CallNonvirtualVoidMethodA) \
    _( 94, GetFieldID) \
    _( 95, GetObjectField) \
    _( 96, GetBooleanField) \
    _( 97, GetByteField) \
    _( 98, GetCharField) \
    _( 99, GetShortField) \
    _(100, GetIntField) \
    _(101, GetLongField) \
    _(102, GetFloatField) \
    _(103, GetDoubleField) \
    _(104, SetObjectField) \
    _(105, SetBooleanField) \
    _(106, SetByteField) \
    _(107, SetCharField) \
    _(108, SetShortField) \
    _(109, SetIntField) \
    _(110, SetLongField) \
    _(111, SetFloatField) \
    _(112, SetDoubleField) \
    _(113, GetStaticMethodID) \
    _(114, CallStaticObjectMethod) \
    _(115, CallStaticObjectMethodV) \
    _(116, CallStaticObjectMethodA) \
    _(117, CallStaticBooleanMethod) \
    _(118, CallStaticBooleanMethodV) \
    _(119, CallStaticBooleanMethodA) \
    _(120, CallStaticByteMethod) \
    _(121, CallStaticByteMethodV) \
    _(122, CallStaticByteMethodA) \
    _(123, CallStaticCharMethod) \
    _(124, CallStaticCharMethodV) \
    _(125, CallStaticCharMethodA) \
    _(126, CallStaticShortMethod) \
    _(127, CallStaticShortMethodV) \
    _(128, CallStaticShortMethodA) \
    _(129, CallStaticIntMethod) \
    _(130, CallStaticIntMethodV) \
    _(131, CallStaticIntMethodA) \
    _(132, CallStaticLongMethod) \
    _(133, CallStaticLongMethodV) \
    _(134, CallStaticLongMethodA) \
    _(135, CallStaticFloatMethod) \
    _(136, CallStaticFloatMethodV) \
    _(137, CallStaticFloatMethodA) \
    _(138, CallStaticDoubleMethod) \
    _(139, CallStaticDoubleMethodV) \
    _(140, CallStaticDoubleMethodA) \
    _(141, CallStaticVoidMethod) \
    _(142, CallStaticVoidMethodV) \
    _(143, CallStaticVoidMethodA) \
    _(144, GetStaticFieldID) \
    _(145, GetStaticObjectField) \
    _(146, GetStaticBooleanField) \
    _(147, GetStaticByteField) \
    _(148, GetStaticCharField) \
    _(149, GetStaticShortField) \
    _(150, GetStaticIntField) \
    _(151, GetStaticLongField) \
    _(152, GetStaticFloatField) \
    _(153, GetStaticDoubleField) \
    _(154, SetStaticObjectField) \
    _(155, SetStaticBooleanField) \
    _(156, SetStaticByteField) \
    _(157, SetStaticCharField) \
    _(158, SetStaticShortField) \
    _(159, SetStaticIntField) \
    _(160, SetStaticLongField) \
    _(161, SetStaticFloatField) \
    _(162, SetStaticDoubleField) \
    _(163, NewString) \
    _(164, GetStringLength) \
    _(165, GetStringChars) \
    _(166, ReleaseStringChars) \
    _(167, NewStringUTF) \
    _(168, GetStringUTFLength) \
    _(169, GetStringUTFChars) \
    _(170, ReleaseStringUTFChars) \
    _(171, GetArrayLength) \
    _(172, NewObjectArray) \
    _(173, GetObjectArrayElement) \
    _(174, SetObjectArrayElement) \
    _(175, NewBooleanArray) \
    _(176, NewByteArray) \
    _(177, NewCharArray) \
    _(178, NewShortArray) \
    _(179, NewIntArray) \
    _(180, NewLongArray) \
    _(181, NewFloatArray) \
    _(182, NewDoubleArray) \
    _(183, GetBooleanArrayElements) \
    _(184, GetByteArrayElements) \
    _(185, GetCharArrayElements) \
    _(186, GetShortArrayElements) \
    _(187, GetIntArrayElements) \
    _(188, GetLongArrayElements) \
    _(189, GetFloatArrayElements) \
    _(190, GetDoubleArrayElements) \
    _(191, ReleaseBooleanArrayElements) \
    _(192, ReleaseByteArrayElements) \
    _(193, ReleaseCharArrayElements) \
    _(194, ReleaseShortArrayElements) \
    _(195, ReleaseIntArrayElements) \
    _(196, ReleaseLongArrayElements) \
    _(197, ReleaseFloatArrayElements) \
    _(198, ReleaseDoubleArrayElements) \
    _(199, GetBooleanArrayRegion) \
    _(200, GetByteArrayRegion) \
    _(201, GetCharArrayRegion) \
    _(202, GetShortArrayRegion) \
    _(203, GetIntArrayRegion) \
    _(204, GetLongArrayRegion) \
    _(205, GetFloatArrayRegion) \
    _(206, GetDoubleArrayRegion) \
    _(207, SetBooleanArrayRegion) \
    _(208, SetByteArrayRegion) \
    _(209, SetCharArrayRegion) \
    _(210, SetShortArrayRegion) \
    _(211, SetIntArrayRegion) \
    _(212, SetLongArrayRegion) \
    _(213, SetFloatArrayRegion) \
    _(214, SetDoubleArrayRegion) \
    _(215, RegisterNatives) \
    _(216, UnregisterNatives) \
    _(217, MonitorEnter) \
    _(218, MonitorExit) \
    _(219, GetJavaVM) \
    _(220, GetStringRegion) \
    _(221, GetStringUTFRegion) \
    _(222, GetPrimitiveArrayCritical) \
    _(223, ReleasePrimitiveArrayCritical) \
    _(224, GetStringCritical) \
    _(225, ReleaseStringCritical) \
    _(226, NewWeakGlobalRef) \
    _(227, DeleteWeakGlobalRef) \
    _(228, ExceptionCheck) \
    _(229, NewDirectByteBuffer) \
    _(230, GetDirectBufferAddress) \
    _(231, GetDirectBufferCapacity) \
    _(232, GetObjectRefType) \
    /* end */

// JNIInvokeInterface (JavaVM) — 8 slots
#define KL_JVM_SLOTS_COUNT 8
#define KL_JVM_SLOTS(_) \
    _(  0, reserved0) \
    _(  1, reserved1) \
    _(  2, reserved2) \
    _(  3, DestroyJavaVM) \
    _(  4, AttachCurrentThread) \
    _(  5, DetachCurrentThread) \
    _(  6, GetEnv) \
    _(  7, AttachCurrentThreadAsDaemon) \
    /* end */

#endif
