// GENERATED by visionos/targets.py — do not edit. Regenerate: make targets
//
// The target table, as the runtime sees it. visionos/targets.py is the
// authority (it also carries the bundle id, product and display name, which
// only the build needs); this is its C half, generated so that the two
// cannot disagree about which tree, which APK or which boot sequence a
// target means. See runtime/kl_target.h for the struct these expand into.

// KL_TARGET_ROW(name, tree, apk, assets, libdir, entry_lib, userdata, obb, kind)
#ifndef KL_TARGET_ROW
#error "include this through runtime/kl_target.c"
#endif

KL_TARGET_ROW("beatsaber", "beatsaber", "beatsaber.apk", "beatsaber/assets", "beatsaber/lib/arm64-v8a", "libmain", "beatsaber", "obb", KL_GUEST_UNITY)
KL_TARGET_ROW("bonelab", "bonelab", "bonelab.apk", "bonelab/assets", "bonelab/lib/arm64-v8a", "libmain", "bonelab", "obb", KL_GUEST_UNITY)
KL_TARGET_ROW("jkxr_ja", "jkxr", "jkxr.apk", "jkxr/assets", "jkxr/lib/arm64-v8a", "libopenjk_ja", "jkxr_ja", "obb", KL_GUEST_JKXR)
KL_TARGET_ROW("jkxr_jo", "jkxr", "jkxr.apk", "jkxr/assets", "jkxr/lib/arm64-v8a", "libopenjk_jo", "jkxr_jo", "obb", KL_GUEST_JKXR)
KL_TARGET_ROW("openbrush", "openbrush", "openbrush.apk", "openbrush/assets", "openbrush/lib/arm64-v8a", "libmain", "openbrush", "obb", KL_GUEST_UNITY)
KL_TARGET_ROW("re4", "re4", "re4.apk", "re4/assets", "re4/lib/arm64-v8a", "libUE4", "re4", "Android/obb/com.Armature.VR4", KL_GUEST_UE4)
KL_TARGET_ROW("steamlink-vr", "steamlink-vr", "steamlink-vr.apk", "steamlink-vr/assets", "steamlink-vr/lib/arm64-v8a", "libvrlink_scene", "steamlink", "obb", KL_GUEST_STEAMLINK)
KL_TARGET_ROW("superhot", "superhot", "superhot.apk", "superhot/assets", "superhot/lib/arm64-v8a", "libmain", "superhot", "obb", KL_GUEST_UNITY)
KL_TARGET_ROW("vrchat", "vrchat", "vrchat.apk", "vrchat/assets", "vrchat/lib/arm64-v8a", "libmain", "vrchat", "obb", KL_GUEST_UNITY)

#define KL_TARGET_DEFAULT_NAME "beatsaber"

