#!/usr/bin/env python3
"""Regenerate runtime/kl_libc_table.h — the direct bionic->Darwin forwards.

A symbol qualifies for a direct forward only if its signature AND every struct it
touches are identical on both platforms. Everything else is hand-written in
kl_libc.c / kl_pthread.c / kl_dl.c, or thunked in kl_va_thunks.S.
"""
import struct, re, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIBS = os.path.join(ROOT, 'beatsaber/lib/arm64-v8a')
GUEST = ['libmain', 'lib_burst_generated', 'libunityopus', 'libunity', 'libil2cpp']

def undefined_symbols(path):
    d = open(path, 'rb').read()
    shoff = struct.unpack_from('<Q', d, 0x28)[0]
    ses, sn, _ = struct.unpack_from('<HHH', d, 0x3a)
    sh = [struct.unpack_from('<IIQQQQIIQQ', d, shoff + i * ses) for i in range(sn)]
    out = set()
    for s in sh:
        if s[1] != 11:                                  # SHT_DYNSYM
            continue
        st = sh[s[6]]
        sd = d[st[4]:st[4] + st[5]]
        for i in range(s[5] // 24):
            n, info, o, shndx, val, sz = struct.unpack_from('<IBBHQQ', d, s[4] + i * 24)
            if n and shndx == 0:
                out.add(sd[n:sd.index(b'\0', n)].decode())
    return out

# Hand-written elsewhere. Keep in sync with the E(...) entries in kl_shim.c.
SPECIAL = set("""
__errno environ gettid __system_property_find __system_property_get __system_property_read
prctl sched_getaffinity sched_setaffinity stat fstat lstat statfs uname sigaction
__FD_ISSET_chk __FD_SET_chk __ctype_get_mb_cur_max lseek64 getpwuid getpwuid_r
opendir readdir closedir setjmp longjmp strtold wcstold strtold_l
swprintf vprintf vsscanf execl syscall sysconf fopen access mkdir unlink rename
dlopen dlsym dlclose dlerror dladdr dl_iterate_phdr
memrchr memalign
fputc fputs fwrite fread fclose fflush fgets getc feof ferror clearerr
fseek fseeko ftell ftello setvbuf
""".split())

PREFIX_SKIP = ('pthread_', 'sem_', '__android_log', 'egl')
RE_SKIP = re.compile(r'^(AAsset|ALooper|ANative|ASensor|AConfig|AInput|gl[A-Z])')

def main():
    allu = set()
    for f in GUEST:
        allu |= undefined_symbols(os.path.join(LIBS, f + '.so'))
    shim = open(os.path.join(ROOT, 'runtime/kl_shim.c')).read()
    listed = set(re.findall(r'E\("([^"]+)"', shim))

    fwd = sorted(s for s in allu
                 if not s.startswith(PREFIX_SKIP)
                 and not RE_SKIP.match(s)
                 and s not in SPECIAL
                 and s not in listed)

    out = os.path.join(ROOT, 'runtime/kl_libc_table.h')
    with open(out, 'w') as f:
        f.write("// GENERATED by tools/gen_libc_table.py -- do not edit.\n")
        f.write("// Direct forwards: signature and struct layouts match Darwin exactly.\n")
        for s in fwd:
            f.write("KL_FWD(%s)\n" % s)
    print("%d direct forwards -> %s" % (len(fwd), out))
    print("%d hand-written / thunked" % len(allu - set(fwd)))

if __name__ == '__main__':
    main()
