#!/usr/bin/env python3
"""Emit runtime/kl_jni_slots.h — the ordered JNI vtable slot lists.

The guest calls JNI through a function table by *index* (libmain's JNI_OnLoad
does `ldr x8,[x8,#0x6b8]` — slot 215, RegisterNatives). So the one thing we
cannot get wrong is the order, and the one authoritative source for it is the
NDK's own jni.h. Transcribing 233 slots by hand is exactly the kind of silent
off-by-one this project has already been bitten by twice, so we parse instead.

Only the names and order are taken from the NDK — no Android header is included
in the build. Regenerate when bumping the NDK; the output is checked in.

    tools/gen_jni_slots.py [path/to/jni.h] > runtime/kl_jni_slots.h
"""
import glob
import os
import re
import sys

NDK_GLOB = os.path.expanduser(
    "~/Library/Android/sdk/ndk/*/toolchains/llvm/prebuilt/*/sysroot/usr/include/jni.h"
)


def find_jni_h():
    hits = sorted(glob.glob(NDK_GLOB))
    if not hits:
        sys.exit("gen_jni_slots: no NDK jni.h found; pass a path explicitly")
    return hits[-1]


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    return re.sub(r"//[^\n]*", " ", text)


def parse_struct(text, tag):
    """Return the member names of `struct <tag>`, in declaration order."""
    m = re.search(r"struct\s+%s\s*\{(.*?)\n\}\s*;" % tag, text, flags=re.S)
    if not m:
        sys.exit("gen_jni_slots: could not find struct %s" % tag)
    slots = []
    for decl in m.group(1).split(";"):
        decl = " ".join(decl.split())
        if not decl:
            continue
        # either `void* reservedN` or `RET (*Name)(args)`
        fn = re.search(r"\(\s*\*\s*(\w+)\s*\)", decl)
        if fn:
            slots.append(fn.group(1))
            continue
        plain = re.match(r"^[\w\s\*]*?(\w+)$", decl)
        if plain:
            slots.append(plain.group(1))
            continue
        sys.exit("gen_jni_slots: unparsed member %r in struct %s" % (decl, tag))
    return slots


def emit(name, macro, slots, out):
    out.append("// %s — %d slots" % (name, len(slots)))
    out.append("#define %s_COUNT %d" % (macro, len(slots)))
    out.append("#define %s(_) \\" % macro)
    for i, s in enumerate(slots):
        out.append("    _(%3d, %s) \\" % (i, s))
    out.append("    /* end */")
    out.append("")


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else find_jni_h()
    text = strip_comments(open(path, encoding="utf-8", errors="replace").read())

    env = parse_struct(text, "JNINativeInterface")
    vm = parse_struct(text, "JNIInvokeInterface")

    out = [
        "// GENERATED by tools/gen_jni_slots.py — do not edit.",
        "// Source: %s" % path.replace(os.path.expanduser("~"), "~"),
        "//",
        "// Slot *order* is ABI. The guest indexes these tables directly; it never",
        "// looks a name up. See runtime/kl_jni.c.",
        "#ifndef KL_JNI_SLOTS_H",
        "#define KL_JNI_SLOTS_H",
        "",
    ]
    emit("JNINativeInterface (JNIEnv)", "KL_JNI_SLOTS", env, out)
    emit("JNIInvokeInterface (JavaVM)", "KL_JVM_SLOTS", vm, out)
    out.append("#endif")

    sys.stdout.write("\n".join(out) + "\n")
    print(
        "gen_jni_slots: %d JNIEnv slots, %d JavaVM slots" % (len(env), len(vm)),
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
