#!/usr/bin/env python3
"""Emit runtime/kl_cacert_table.h — the host's root CA anchors, as DER.

The guest's HTTPS stack (unitytls, reached through UnityWebRequest and Mono's
MobileAuthenticatedStream alike) asks Android for the *system* trust store:

    TrustManagerFactory.getInstance(getDefaultAlgorithm()).init(null)
      .getTrustManagers()[0]                  -> javax/net/ssl/X509TrustManager
      .getAcceptedIssuers()                   -> [Ljava/security/cert/X509Certificate;
        .getEncoded()                         -> [B, one DER blob per anchor

All three names are in libunity.so; `checkServerTrusted` is NOT, so unitytls
takes the anchors as a CA bundle and does the chain validation itself. That is
what makes serving real roots safe: we supply the trust *set*, not the verdict.

Why this is baked rather than read at runtime:

    SecTrustCopyAnchorCertificates is __IPHONE_NA. macOS can enumerate its own
    trust store and visionOS cannot, and there is no public replacement — so
    reading the live store would mean the host and the device sourcing trust
    differently, which is the exact shape of divergence this project keeps
    paying for. One table, generated on a Mac, compiled into both.

The source is SecTrustCopyAnchorCertificates rather than the
SystemRootCertificates keychain: the keychain carries 158 certificates and
SecTrust hands out 157, because a root that is present is not necessarily a
root the system trusts. Trust settings are the authority; the file is not.

Roots expire and get withdrawn. Regenerate deliberately with `make cacerts`;
the output is checked in, so a build never needs the host keychain (and the
visionOS build could not use it anyway).

    tools/gen_cacerts.py > runtime/kl_cacert_table.h
"""
import ctypes
import ctypes.util
import datetime
import platform
import sys

kCFStringEncodingUTF8 = 0x08000100


def load():
    sec = ctypes.CDLL(ctypes.util.find_library("Security"))
    cf = ctypes.CDLL(ctypes.util.find_library("CoreFoundation"))

    cf.CFArrayGetCount.restype = ctypes.c_long
    cf.CFArrayGetCount.argtypes = [ctypes.c_void_p]
    cf.CFArrayGetValueAtIndex.restype = ctypes.c_void_p
    cf.CFArrayGetValueAtIndex.argtypes = [ctypes.c_void_p, ctypes.c_long]
    cf.CFDataGetLength.restype = ctypes.c_long
    cf.CFDataGetLength.argtypes = [ctypes.c_void_p]
    cf.CFDataGetBytePtr.restype = ctypes.c_void_p
    cf.CFDataGetBytePtr.argtypes = [ctypes.c_void_p]
    cf.CFRelease.argtypes = [ctypes.c_void_p]
    cf.CFStringGetCString.restype = ctypes.c_bool
    cf.CFStringGetCString.argtypes = [
        ctypes.c_void_p, ctypes.c_char_p, ctypes.c_long, ctypes.c_uint32]

    sec.SecTrustCopyAnchorCertificates.restype = ctypes.c_int32
    sec.SecTrustCopyAnchorCertificates.argtypes = [ctypes.c_void_p]
    sec.SecCertificateCopyData.restype = ctypes.c_void_p
    sec.SecCertificateCopyData.argtypes = [ctypes.c_void_p]
    sec.SecCertificateCopySubjectSummary.restype = ctypes.c_void_p
    sec.SecCertificateCopySubjectSummary.argtypes = [ctypes.c_void_p]
    return sec, cf


def anchors():
    sec, cf = load()
    arr = ctypes.c_void_p()
    st = sec.SecTrustCopyAnchorCertificates(ctypes.byref(arr))
    if st != 0 or not arr:
        sys.exit(f"gen_cacerts: SecTrustCopyAnchorCertificates failed ({st})")

    out = []
    for i in range(cf.CFArrayGetCount(arr)):
        cert = cf.CFArrayGetValueAtIndex(arr, i)

        data = sec.SecCertificateCopyData(cert)
        if not data:
            continue
        n = cf.CFDataGetLength(data)
        der = ctypes.string_at(cf.CFDataGetBytePtr(data), n)
        cf.CFRelease(data)

        name = ""
        summary = sec.SecCertificateCopySubjectSummary(cert)
        if summary:
            buf = ctypes.create_string_buffer(512)
            if cf.CFStringGetCString(summary, buf, len(buf), kCFStringEncodingUTF8):
                name = buf.value.decode("utf-8", "replace")
            cf.CFRelease(summary)
        out.append((der, name))

    cf.CFRelease(arr)
    # Sort by subject so an unrelated reordering in the keychain does not show
    # up as a whole-file diff. The set is what matters; the order never is.
    out.sort(key=lambda t: (t[1], t[0]))
    return out


def sanitize(s):
    # This lands inside a /* */ comment and must not close it, and non-ASCII
    # subject summaries exist ("Chambers of Commerce Root - 2008" is fine,
    # "Autoridad de Certificación Firmaprofesional" is not, in a C89 comment).
    s = s.replace("*/", "* /")
    return "".join(c if 0x20 <= ord(c) < 0x7F else "?" for c in s)


def main():
    certs = anchors()
    total = sum(len(der) for der, _ in certs)

    w = sys.stdout.write
    w("// GENERATED by tools/gen_cacerts.py — do not edit.\n")
    w("//\n")
    w("// The host's root CA anchors, as DER, for the synthetic Android trust\n")
    w("// store in kl_cacerts.c. See that file for what consumes them, and the\n")
    w("// generator for why they are baked rather than read at runtime\n")
    w("// (SecTrustCopyAnchorCertificates is __IPHONE_NA — visionOS cannot\n")
    w("// enumerate its own store, so the host and the device would otherwise\n")
    w("// source trust differently).\n")
    w("//\n")
    w(f"// source:  SecTrustCopyAnchorCertificates on macOS {platform.mac_ver()[0]}\n")
    w(f"// dated:   {datetime.date.today().isoformat()}\n")
    w(f"// anchors: {len(certs)}, {total} bytes of DER\n")
    w("//\n")
    w("// Roots expire and get withdrawn. `make cacerts` regenerates.\n")
    w("\n")
    w(f"#define KL_CACERT_COUNT {len(certs)}\n\n")

    w("static const unsigned char kl_cacert_der[] = {")
    blob = b"".join(der for der, _ in certs)
    for i, b in enumerate(blob):
        if i % 16 == 0:
            w("\n    ")
        w(f"0x{b:02x},")
    w("\n};\n\n")

    w("static const struct { unsigned int off, len; } kl_cacert_span[KL_CACERT_COUNT] = {\n")
    off = 0
    for der, name in certs:
        w(f"    {{ {off:6d}, {len(der):5d} }},  /* {sanitize(name)} */\n")
        off += len(der)
    w("};\n")

    assert off == total
    print(f"gen_cacerts: {len(certs)} anchors, {total} bytes of DER",
          file=sys.stderr)


if __name__ == "__main__":
    main()
